version: "3.9"
services:
  web:
    build: .
    ports:
      - "1010:5000"
    volumes:
      - type: bind
        source: ./images
        target: /ImageResize/images
      - type: bind
        source: ./logs
        target: /ImageResize/logs