version: "3.9"
services:
  web:
    image: imageresize
    build: .
    ports:
      - "5000:5000"
    volumes:
      - type: bind
        source: ./images
        target: /ImageResize/images
      - type: bind
        source: ./logs
        target: /ImageResize/logs
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
  worker:
    image: imageresize:latest
    depends_on: 
      - redis
    command: rq worker --url redis://redis:6379
    links:
      - redis
    volumes:
      - type: bind
        source: ./images
        target: /ImageResize/images
      - type: bind
        source: ./logs
        target: /ImageResize/logs